### ISSUE TITLE
// TODO / Design / SEO / UI

### ISSUE THREAD

**Issue by siljeangelvik** [siljeangelvik/react-antd-holidaze-exam#2]
- [x] Add view-port to meta data in HTML for a better mobile experience.

- [x] Add meta-content to the HTML.

- [x] Change the fav.icon to a more "project-friendly" logo.

- [x] Change the text on the Login "Submit" button.

- [x] Change the text on the Registration "Submit" button.

- [x] Make the "Back" Button on the Details-page bigger.

- [x] Make the mobile menu display the registered user avatar.

- [x] Make a carousel on the Details-page, if the media property has more than one value.
