### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by siljeangelvik** [siljeangelvik/react-antd-holidaze-exam#3]
- [x] **RegistrationForm:** If input value !validEmail, display message: not valid for registration 
- [x] **LoginForm:** If email input value does not match a registered user, display message: User doesn't exist

- [x] **BookingForm:** When user successfully creates a booking request, display _BookingSuccess_ notification 

- [ ] **VenueForm:** When user successfully creates a new venue request, display _VenueCreatedSuccess_ notification 

- [x] **Buttons:** text alignment centre

- [x] **Logo:** State changes on browser refresh 

- [ ] **Bookings:** State doesn't update until user logs out and back in or if user refresh's page 

- [ ] **Venues:** State doesn't update until User logs out and back in or if user refreshes the page 

- [x] **Navbar:** Make the mobile navbar wider

- [ ] **SuccessBooking:** Add padding to the modal

- [ ] **CreateVenue:** Add padding and scrolling option to the modal

- [ ] **SuccessRegistered:** Add type=submit and import the component to the Registration-form

**EXTRA (NICE TO HAVE)**

- [ ] **FilterSearch:** venue.name, venue.price, venue.owner.name, venue.location.country, venue.location.city

- [x] **DetailsPage:** Add a media carousel with next and previous buttons
